# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish

on:
  release:
    types: [created]

jobs:
  npm_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          registry-url: https://registry.npmjs.org/
          always-auth: true
      - run: yarn install && yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
  docker_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn install && yarn build
      - run: |
              docker build . --file Dockerfile --tag ghcr.io/technokrat/vuexr/vuexr:${{  github.ref_name }} --tag ghcr.io/technokrat/vuexr/vuexr:latest
              docker push ghcr.io/technokrat/vuexr/vuexr:${{  github.ref_name }}
              docker push ghcr.io/technokrat/vuexr/vuexr:latest
